name: ReallifePlugin
version: ${project.version}
description: A bukkit reallife plugin
author: Trojaner
website: http://static-interface.de
main: de.static_interface.reallifeplugin.ReallifeMain
depend: [SinkLibrary, WorldGuard]
soft-depend: [AdventuriaPlugin]

commands:
  ic:
    description: Insurance Command
    permission: reallifeplugin.insurance
    usage: "Wrong usage! Correct Usage: /<command> <on/off>"
    aliases: [insurance]
  sm:
    description: Stockmarkets
    aliases: stockmarket
    permission: reallifeplugin.stockmarket
  level:
    description: Level command
    permission: reallifeplugin.levelcommand
  party:
    description: Party command
    permission: reallifeplugin.party

permissions:
  reallifeplugin.command:
     default: op
  reallifeplugin.insurance:
     default: true
  reallifeplugin.escapebypass:
     default: false
  reallifeplugin.corporation:
     default: true
  reallifeplugin.ad:
     default: true
  reallifeplugin.stockmarket:
     default: true
  reallifeplugin.contract:
     default: true
  reallifeplugin.levelcommand:
     default: true
  reallifeplugin.party:
     default: true